//! The engine facade: the only surface exposed across the language boundary.
//!
//! Everything the Flutter client can do goes through the DTOs and job handles
//! defined here. Internal crates stay free to change because the generated
//! bridge bindings only ever see this crate.
//!
//! `flutter_rust_bridge` is configured (see `flutter_rust_bridge.yaml` at the
//! repository root) to scan the `dto` and `facade` modules and emit the Dart
//! bindings into
//! `app/lib/src/bridge/generated/`. Generated files are never hand-edited and
//! never committed; regenerate them with `tools/generate-bridge.sh`.

mod convert;
mod dto;
mod facade;
mod jobs;
#[cfg(all(target_os = "macos", feature = "macos-tflite-eval"))]
mod player_tracking_job;
pub mod track_artifact;

// Generated by `tools/generate-bridge.sh` from flutter_rust_bridge.yaml. The
// file is not committed and is compiled only into the `bridge` build, so an
// engine-only checkout works with no Dart toolchain present.
//
// The allow is limited to this generated module: it contains the FFI entry
// points, which are necessarily `unsafe`. Nothing hand-written in the engine
// uses unsafe code.
#[allow(unsafe_code)]
#[cfg(feature = "bridge")]
mod frb_generated;

/// The bridge surface.
///
/// This module is the verbatim input to code generation, so it re-exports the
/// DTOs and the facade functions and nothing else.
pub mod api {
    pub use crate::dto::*;
    pub use crate::facade::*;
}

pub use dto::*;
pub use facade::*;
